In [1]:
import os
import pandas
count_line = 0

In [2]:
views_df = pandas.read_csv('~/Downloads/customer_product_date.csv', sep='\t', header=None, names = ['cid', 'pid', 'dates'])

In [3]:
views_df = views_df[['cid', 'pid']]

In [4]:
views_df

                cid      pid
0          69112500    52840
2         103311350    52840
4          13341550    52840
6           2077600    52840
8         110704650    59681
12         56070450    59700
17         76526400    79225
18          6516850    85441
20         39884400    85441
22         72081750    85441
24          7436850    85441
26         22563750    85441
28         47392800    85441
30         57574800    85441
32         53653350    85441
34         59134050    85441
36         22437450    85441
38         22437450    85441
40         67546200    85441
42         32309250    85441
44        108128950    85441
46         44923350    85441
48          6927900    85441
50         49771650    97242
52         49771650    97242
54         49771650    97242
56         14441550    97242
58         21174150    97242
60         10783850    97242
62         28016550    97242
...             ...      ...
49497730  103829600  6473677
49497731   46858500  6473677
49497732  109455600  6473677
49497733   29322600  6473677
49497734   31365750  6473677
49497735   56473200  6473677
49497736  106450800  6473677
49497737   61423350  6473677
49497738   51841800  6473677
49497739   61423350  6473677
49497740   61423350  6473677
49497741   15670500  6473677
49497742   45574200  6473677
49497743   19304400  6473677
49497744   11243700  6473677
49497745  104930500  6473677
49497746    3756150  6473677
49497747    3756150  6473677
49497748   24726450  6473677
49497749   70590450  6473953
49497750  104181100  6473953
49497751   38926950  6473953
49497752   35575350  6473953
49497753  101178450  6473953
49497754  109634000  6473953
49497755   66593100  6473953
49497756   21114600  6473953
49497757   58339950  6473953
49497758   74720250  6473953
49497759   55770000  6473953

[47112333 rows x 2 columns]

In [5]:
views_gb = views_df.groupby(['cid', 'pid']).size().reset_index(name="cnt")

In [7]:
views_gb

                cid      pid  cnt
0                50  4547366    1
1                50  4566011    1
2                50  4807130    1
3                50  4964126    1
4                50  5015929    4
5                50  5045958    4
6                50  5110931    1
7                50  5111124    1
8                50  5163444    1
9                50  5164030    1
10               50  5168576    1
11               50  5224063    1
12               50  5243818    1
13               50  5246078    1
14               50  5347847    1
15               50  5348227    1
16               50  5378611    1
17               50  5441969    1
18               50  5452128    1
19               50  5540743    1
20               50  5552438    1
21               50  5552630    1
22               50  5613057    1
23               50  5625515    1
24               50  5689317    1
25               50  5758061    1
26               50  5758062    4
27               50  5758068    1
28              150  1556321    1
29              150  1556326    1
...             ...      ...  ...
33835427  113701600  5622572    1
33835428  113701600  5641355    1
33835429  113701600  5641624    1
33835430  113701600  5687510    1
33835431  113701600  5693033    1
33835432  113701600  5693277    1
33835433  113701600  5693285    1
33835434  113701600  5693699    1
33835435  113701600  5693884    1
33835436  113701600  5694020    1
33835437  113701600  5713818    1
33835438  113701600  5714225    1
33835439  113701600  5766909    1
33835440  113701600  5767039    1
33835441  113701600  5786087    1
33835442  113701600  6110133    1
33835443  113701600  6117280    1
33835444  113701600  6190710    1
33835445  113702250  5852395    1
33835446  113702250  5916252    1
33835447  113702250  6039612    1
33835448  113702250  6285980    1
33835449  113703700  5266100    1
33835450  113703700  5840963    1
33835451  113703700  5926372    1
33835452  113703700  6051023    1
33835453  113704150  5714335    1
33835454  113704150  5797355    1
33835455  113704500  5784152    1
33835456  113704900  3582048    1

[33835457 rows x 3 columns]

In [14]:
views_gb.to_csv('~/Documents/customer_product_rating.csv', header=None)